logging:
  output_dir: ../output/chess_game
manager:
  args:
    max_player_attempts: 5
    max_rounds: 200
    win_conditions: 
      - Checkmate
    draw_conditions:
      - Stalemate
      - ThreefoldRepetition
      - FiftyMoveRule
      - InsufficientMaterial
game:
  name: chess
  players:
    - name: chess_player
      args:
        id: llama3.3 70b white
        roles:
          - name: White
            optimize: false
            metric: chess_move_validation_metric
            dataset: chess_dataset
            dataset_args:
              filename: ./data/chess/stockfish_examples.jsonl
              role: White
              num_examples: 10
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        lm:
          model: openrouter/meta-llama/llama-3.3-70b-instruct
        max_tries: 5
    - name: chess_player
      args:
        id: llama3.1 70b black
        roles:
          - name: Black
            optimize: false
            metric: chess_move_validation_metric
            dataset: chess_dataset
            dataset_args:
              filename: ./data/chess/stockfish_examples.jsonl
              role: Black
              num_examples: 10
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        lm:
          model: openrouter/meta-llama/llama-3.1-70b-instruct
        max_tries: 5
