logging:
  output_dir: ../output/chess_game
manager:
  args:
    max_rounds: 200
    win_conditions:
      - Checkmate
    draw_conditions:
      - Stalemate
      - ThreefoldRepetition
      - FiftyMoveRule
      - InsufficientMaterial
game:
  name: chess
  players:
    - name: chess_player
      args:
        id: gpt4 white
        roles:
          - White
        optimize: true
        dataset: chess_puzzle_dataset
        dataset_args:
          role: White
          num_samples: 50
        optimizer: BootstrapFewShot
        optimizer_args:
          max_bootstrapped_demos: 3
          max_labeled_demos: 3
        metric: chess_stockfish_metric
        lm:
          type: OpenAI
          args:
            model: gpt-4o-mini
            model_type: chat
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
        max_tries: 5
    - name: chess_player
      args:
        id: gpt4 black
        roles:
          - Black
        optimize: true
        dataset: chess_puzzle_dataset
        dataset_args:
          role: Black
          num_samples: 50
        optimizer: BootstrapFewShot
        optimizer_args:
          max_bootstrapped_demos: 3
          max_labeled_demos: 3
        metric: chess_stockfish_metric
        lm:
          type: OpenAI
          args:
            model: gpt-4o-mini
            model_type: chat
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
        max_tries: 5
