logging:
  output_dir: /Users/haidark/ktet_src/output/chess_matches
manager:
  name: rating_games
  match_manager_args:
    max_matches: 3
    max_rounds: 1000
    starting_elo: 800
    matching: round_robin
  game_manager_args:
    max_player_attempts: 5
    max_rounds: 200
    win_conditions: 
      - Checkmate
      - Invalid
    draw_conditions:
      - Stalemate
      - Insufficient material
      - 75-move rule
      - Fivefold repetition
game:
  name: chess
  players:
    - name: chess_player
      args:
        id: white
        roles:
          - White
        optimize: false
        datasets:
          - dataset: chess_dataset
            dataset_args:
              filename: ./data/chess/stockfish_examples.jsonl
              role: White
            metric: chess_move_validation_metric
            optimizer: MIPROv2
            optimizer_args:
              num_candidates: 5
              minibatch_size: 20
              minibatch_full_eval_steps: 10
            compilation_args:
              max_bootstrapped_demos: 1
              max_labeled_demos: 1
        max_tries: 5

    - name: chess_player
      args:
        id: black
        roles:
          - Black
        optimize: false
        datasets:
          - dataset: chess_dataset
            dataset_args:
              filename: ./data/chess/stockfish_examples.jsonl
              role: Black
            metric: chess_move_validation_metric
            optimizer: MIPROv2
            optimizer_args:
              num_candidates: 5
              minibatch_size: 20
              minibatch_full_eval_steps: 10
            compilation_args:
              max_bootstrapped_demos: 1
              max_labeled_demos: 1
        max_tries: 5

llms:
  - type: AzureOpenAI
    name: gpt-4o1
    args:
      api_base: https://allam-swn-gpt-01.openai.azure.com/
      api_version: 2023-07-01-preview
      deployment_id: gpt-4o-900ptu
      max_tokens: 800
      temperature: 0.8
      top_p: 0.95
      frequency_penalty: 0
      presence_penalty: 0
  - type: AzureOpenAI
    name: gpt-4o2
    args:
      api_base: https://allam-swn-gpt-01.openai.azure.com/
      api_version: 2023-07-01-preview
      deployment_id: gpt-4o-900ptu
      max_tokens: 800
      temperature: 0.8
      top_p: 0.95
      frequency_penalty: 0
      presence_penalty: 0
  # - type: Claude
  #   name: claude-3-5-sonnet
  #   args:
  #     model: claude-3-5-sonnet-20240620
  #     max_tokens: 800
  #     temperature: 0.8
  #     top_p: 0.95
