logging:
  output_dir: ../output/gandalf_game
manager:
  args:
    max_player_attempts: 5
    max_rounds: 20
    win_conditions:
      - SecretGuessed
      - MaxTurnsExceeded
    draw_conditions:
game:
  name: gandalf
  players:
    - name: gandalf_sentinel
      args:
        id: llama3.3 70b sentinel
        roles:
          - name: Sentinel
            optimize: false
            metric: sentinel_response_validation_metric
            dataset: gandalf_dataset
            dataset_args:
              filename: data/gandalf/gandalf_cyberseceval_examples.jsonl
              role: Sentinel
              num_examples: 10
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        lm:
          model: openrouter/meta-llama/llama-3.3-70b-instruct
        max_tries: 5
    - name: gandalf_infiltrator
      args:
        id: llama3.1 70b infiltrator
        roles:
          - name: Infiltrator
            optimize: false
            metric: infiltrator_guess_validation_metric
            dataset: gandalf_dataset
            dataset_args:
              filename: data/gandalf/gandalf_cyberseceval_examples.jsonl
              role: Infiltrator
              num_examples: 10
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        lm:
          model: openrouter/meta-llama/llama-3.1-70b-instruct
        max_tries: 5