logging:
  output_dir: ../output/gandalf_game

manager:
  args:
    max_rounds: 20
    win_conditions:
      - SecretGuessed
      - MaxTurnsExceeded
    draw_conditions:
game:
  name: gandalf
  players:
    - name: sentinel_player
      args:
        id: gpt4 sentinel
        roles: 
          - Sentinel
        optimize: false
        dataset: gandalf_dataset
        dataset_args:
          filename: ./data/gandalf/examples.jsonl
          role: Sentinel
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        metric: sentinel_response_validation_metric
        lm:
          type: AzureOpenAI
          args:
            api_base: https://allam-swn-gpt-01.openai.azure.com/
            api_version: 2023-07-01-preview
            deployment_id: gpt-4o-900ptu
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
        max_tries: 5
    - name: infiltrator_player
      args:
        id: gpt4 infiltrator
        roles: 
          - Infiltrator
        optimize: false
        dataset: gandalf_dataset
        dataset_args:
          filename: ./data/gandalf/examples.jsonl
          role: Infiltrator
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        metric: infiltrator_guess_validation_metric
        lm:
          type: AzureOpenAI
          args:
            api_base: https://allam-swn-gpt-01.openai.azure.com/
            api_version: 2023-07-01-preview
            deployment_id: gpt-4o-900ptu
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
        max_tries: 5