manager:
  output_dir: ../output/liars_dice_game
  max_player_attempts: 5
  max_rounds: 100
game:
  name: liars_dice
  args:
    num_dice: 5  # Number of dice per player
    players:
      player_0:
        class: liars_dice_player
        args:
          id: llama3.3 70b player0
          lm:
            model: openrouter/meta-llama/llama-3.3-70b-instruct
            cache: None
          max_tries: 5
      player_1:
        class: liars_dice_player
        args:
          id: llama3.1 70b player1
          lm:
            model: openrouter/meta-llama/llama-3.1-70b-instruct
            cache: None
          max_tries: 5
