logging:
  output_dir: ../output/mathquiz_game
manager:
  args:
    max_player_attempts: 5
    max_rounds: 100
game:
  name: mathquiz
  args:
    players:
      teacher:
        name: mathquiz_teacher
        args:
          id: llama3.1 teacher
          # actions: 
          #   - name: TeacherGenerateQuestion
          #     optimize: true
          #     metric: math_question_validation_metric
          #     dataset: mathquiz_dataset
          #     dataset_args:
          #       filename: data/mathquiz/mathquiz_hendrycks-math_examples.jsonl
          #       # filename: data/mathquiz/mathquiz_gsm8k_examples.jsonl
          #       role: TeacherGenerateQuestion
          #       num_examples: 10
          #   - name: TeacherAnswerQuestion
          #     metric: math_answer_validation_metric
          #     dataset: mathquiz_dataset
          #     dataset_args:
          #       filename: data/mathquiz/mathquiz_hendrycks-math_examples.jsonl
          #       # filename: data/mathquiz/mathquiz_gsm8k_examples.jsonl
          #       role: TeacherAnswerQuestion
          # optimizer: BootstrapFewShotWithRandomSearch
          lm:
            model: openrouter/meta-llama/llama-3.3-70b-instruct
          max_tries: 5
      student:
        name: mathquiz_student
        args:
          id: llama3.1 student
          # actions: 
          #   - name: StudentAnswerQuestion
          #     optimize: false
          #     metric: math_answer_validation_metric
          #     dataset: mathquiz_dataset
          #     dataset_args:
          #       filename: data/mathquiz/mathquiz_hendrycks-math_examples.jsonl
          #       # filename: data/mathquiz/mathquiz_gsm8k_examples.jsonl
          #       role: StudentAnswerQuestion
          #       num_examples: 10
          # optimizer: BootstrapFewShotWithRandomSearch
          lm:
            model: openrouter/meta-llama/llama-3.1-70b-instruct
          max_tries: 5
