logging:
  output_dir: ../output/mathquiz_game
manager:
  args:
    max_rounds: 10
    win_conditions:
      - StudentCorrect
    draw_conditions:
game:
  name: mathquiz
  players:
    - name: mathquiz_teacher
      args:
        id: gpt4 teacher
        roles: 
          - TeacherGenerateQuestion
          - TeacherAnswerQuestion
        optimize: false
        dataset: mathquiz_dataset
        dataset_args:
          filename: ./data/mathquiz/examples.jsonl
          role: Teacher
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        metric: math_question_validation_metric
        lm:
          type: AzureOpenAI
          args:
            api_base: https://allam-swn-gpt-01.openai.azure.com/
            api_version: 2023-07-01-preview
            deployment_id: gpt-4o-900ptu
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
        max_tries: 5
    - name: mathquiz_student
      args:
        id: gpt4 student
        roles: 
          - StudentAnswerQuestion
        optimize: false
        dataset: mathquiz_dataset
        dataset_args:
          filename: ./data/mathquiz/examples.jsonl
          role: Student
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        metric: math_answer_validation_metric
        lm:
          type: AzureOpenAI
          args:
            api_base: https://allam-swn-gpt-01.openai.azure.com/
            api_version: 2023-07-01-preview
            deployment_id: gpt-4o-900ptu
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
        max_tries: 5
