logging:
  output_dir: ../output/mathquiz_game
manager:
  args:
    max_rounds: 100
    win_conditions:
      - StudentCorrect
    draw_conditions:
game:
  name: mathquiz
  players:
    - name: mathquiz_teacher
      args:
        id: llama3.1 teacher
        roles: 
          - TeacherGenerateQuestion
          - TeacherAnswerQuestion
        optimize: true
        datasets:
        - dataset: mathquiz_dataset
          dataset_args:
            filename: data/mathquiz/mathquiz_hendrycks-math_examples.jsonl
            # filename: data/mathquiz/mathquiz_gsm8k_examples.jsonl
            role: TeacherGenerateQuestion
            num_examples: 10
          metric: math_question_validation_metric
          optimizer: BootstrapFewShotWithRandomSearch
        - dataset: mathquiz_dataset
          dataset_args:
            filename: data/mathquiz/mathquiz_hendrycks-math_examples.jsonl
            # filename: data/mathquiz/mathquiz_gsm8k_examples.jsonl
            role: TeacherAnswerQuestion
            num_examples: 10
          metric: math_answer_validation_metric
          optimizer: BootstrapFewShotWithRandomSearch
          # optimizer_args:
          #   num_candidates: 5
          #   minibatch_size: 5
          #   minibatch_full_eval_steps: 10
          # compilation_args:
          #   max_bootstrapped_demos: 1
          #   max_labeled_demos: 1
        lm:
          type: OllamaLocal
          args:
            model: llama3.1
            base_url: http://localhost:11434
        max_tries: 5
    - name: mathquiz_student
      args:
        id: llama3.1 student
        roles: 
          - StudentAnswerQuestion
        optimize: true
        datasets:
        - dataset: mathquiz_dataset
          dataset_args:
            filename: data/mathquiz/mathquiz_hendrycks-math_examples.jsonl
            # filename: data/mathquiz/mathquiz_gsm8k_examples.jsonl
            role: StudentAnswerQuestion
            num_examples: 10
          metric: math_answer_validation_metric
          optimizer: BootstrapFewShotWithRandomSearch
          # optimizer_args:
          #   num_candidates: 5
          #   minibatch_size: 20
          #   minibatch_full_eval_steps: 10
          # compilation_args:
          #   max_bootstrapped_demos: 1
          #   max_labeled_demos: 1
        lm:
          type: OllamaLocal
          args:
            model: llama3.1
            base_url: http://localhost:11434
        max_tries: 5
