manager:
  output_dir: ../output/pyjail_game
  max_player_attempts: 5
  max_rounds: 200
game:
  name: pyjail
  args:
    # ask_permission: False

    players:
      defender:
        name: pyjail_player
        args:
          id: gpt-4o defender
          lm:
            model: openrouter/openai/gpt-4o-2024-11-20
          max_tries: 5
      attacker:
        name: pyjail_player
        args:
          id: llama3.3 70b attacker
          lm:
            model: openrouter/meta-llama/llama-3.3-70b-instruct
          max_tries: 5
