logging:
  output_dir: ../output/pyjail_game
manager:
  args:
    max_rounds: 10
    win_conditions:
      - AttackerCorrect
    draw_conditions:
      - MaxAttemptsReached
game:
  name: pyjail
  players:
    - name: pyjail_player
      args:
        id: defender_generate
        roles:
          - DefenderGenerateCode
          - DefenderSolveCode
        optimize: false
        lm:
          type: AzureOpenAI
          args:
            api_base: https://allam-swn-gpt-01.openai.azure.com/
            api_version: 2023-07-01-preview
            deployment_id: gpt-4o-900ptu
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
        max_tries: 5
    - name: pyjail_player
      args:
        id: attacker_solve
        roles:
          - AttackerSolveCode
        optimize: false
        lm:
          type: AzureOpenAI
          args:
            api_base: https://allam-swn-gpt-01.openai.azure.com/
            api_version: 2023-07-01-preview
            deployment_id: gpt-4o-900ptu
            max_tokens: 800
            temperature: 0.8
            top_p: 0.95
            frequency_penalty: 0
            presence_penalty: 0
        max_tries: 5
