logging:
  output_dir: ../output/pyjail_game
manager:
  args:
    max_player_attempts: 5
    max_rounds: 10
    win_conditions:
      - AttackerCorrect
    draw_conditions:
      - MaxAttemptsReached
game:
  name: pyjail
  players:
    - name: pyjail_player
      args:
        id: llama3.3 70b defender
        roles:
          - name: DefenderGenerateCode
            optimize: false
            metric: pyjail_code_validation_metric
            dataset: pyjail_dataset
            dataset_args:
              filename: data/pyjail/pyjail_examples.jsonl
              role: DefenderGenerateCode
              num_examples: 10
          - name: DefenderSolveCode
            optimize: false
            metric: pyjail_solution_validation_metric
            dataset: pyjail_dataset
            dataset_args:
              filename: data/pyjail/pyjail_examples.jsonl
              role: DefenderSolveCode
              num_examples: 10
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        lm:
          model: openrouter/meta-llama/llama-3.3-70b-instruct
        max_tries: 5
    - name: pyjail_player
      args:
        id: llama3.1 70b attacker
        roles:
          - name: AttackerSolveCode
            optimize: false
            metric: pyjail_solution_validation_metric
            dataset: pyjail_dataset
            dataset_args:
              filename: data/pyjail/pyjail_examples.jsonl
              role: AttackerSolveCode
              num_examples: 10
        optimizer: MIPROv2
        optimizer_args:
          num_candidates: 5
          minibatch_size: 20
          minibatch_full_eval_steps: 10
        compilation_args:
          max_bootstrapped_demos: 1
          max_labeled_demos: 1
        lm:
          model: openrouter/meta-llama/llama-3.1-70b-instruct
        max_tries: 5
